name: Push changes to upstream subtree
on: [push]

jobs:
  trigger-index-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -x POST -H "Authorization: token ${GH_WORKFLOW_PAT}" -H "Content-Type: application/json" \
          https://api.github.com/repos/infogulch/index/dispatches \
          -d '{"event_type": "notebooks_push"}'

